# variables:
#   ServiceConnectionName: '<serviceconnection>'
#   Location: '<location>'
#   ResourceGroup: '<resourcegroup>'
#   AppName: '<appName>' # less or equal than 11 chars
#   DeployAzureResources: false
#   DeployableSourceBranch: 'refs/heads/staging'
#   SlotName: '<slotName>'

name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  branches:
    include:
    - staging
    - azdo
    - feature/* # ci-only

resources:
- repo: self

stages:

# CI
- stage: Build
  jobs:
  - job: dronestatusjobci
    displayName: "Drone Status CI"
    steps:
    - template: ./src/DroneStatus/azure-pipelines-ci.yml

# CD
- stage: Deploy
  dependsOn: Build
  condition: and(succeeded('Build'), eq(variables['build.sourceBranch'], variables['DeployableSourceBranch']))
  jobs:
  - template: ./src/DroneStatus/azure-pipelines-cd.yml
  # - job: dronestatuscd
  #   displayName: "Drone Status CD"
  #   steps:
    # - script: |
    #     echo 'Hello!'
    #   displayName: 'Stub'
    #   name: stub

